Repository Oxyopiia/ViceMod, pull requests merged in 2025-02, with the labels that each got.

#102 Update On the Run warp tooltip color
  src/main/java/net/oxyopia/vice/data/Colors.kt
  src/main/java/net/oxyopia/vice/features/misc/BetterWarpMenu.kt
Labels: size: XS

#103 Update build-artifact in build.yml to v4
  .github/workflows/build.yml
Labels: size: XS

#104 Added Galvaniser and Unstable Dynamite Barrel to Ability Cooldown
  src/main/java/net/oxyopia/vice/features/itemabilities/ItemAbility.kt
  src/main/java/net/oxyopia/vice/features/itemabilities/ItemAbilityCooldown.kt
Labels: size: S

#101 Fixed Starry Quarry Bound
  src/main/java/net/oxyopia/vice/features/hud/CaveInPrediction.kt
Labels: size: XS

#106 Updated cooldown of Starblade from 5s to 2s
  src/main/java/net/oxyopia/vice/features/itemabilities/ItemAbility.kt
Labels: size: XS

#109 Improved /vice dev color
  src/main/java/net/oxyopia/vice/commands/ViceCommand.kt
Labels: size: M
